const leagues = {
  urc: { name:'United Rugby Championship', short:'URC', intro:'The best of Europe, together.', description:'Watch every URC fixture with official broadcast links, live status and match-day notes.', matches:[['Leinster','Bulls','LIVE · 2ND HALF · 58:14',true,'URC TV','https://www.unitedrugby.com/'],['Munster','Edinburgh','TOMORROW · 17:15 UTC',false,'URC TV','https://www.unitedrugby.com/']] },
  top14: { name:'Top 14', short:'TOP 14', intro:'France plays its own game.', description:'Your home for Top 14 fixtures, live coverage and the official place to watch.', matches:[['Toulouse','La Rochelle','TODAY · 20:05 UTC',false,'France TV','https://www.france.tv/sport/'],['Bordeaux','Racing 92','TOMORROW · 19:00 UTC',false,'France TV','https://www.france.tv/sport/']] },
  superRugby: { name:'Super Rugby Pacific', short:'SUPER RUGBY', intro:'Fast, bright, wide open.', description:'Track the Pacific game with match times and official regional viewing links.', matches:[['Blues','Crusaders','TODAY · 08:35 UTC',false,'NZR+','https://www.nzrugby.co.nz/'],['Reds','Brumbies','SATURDAY · 09:05 UTC',false,'Stan Sport','https://www.rugby.com.au/']] },
  womens: { name:"Women's Rugby", short:'WOMEN’S', intro:'The future is already here.', description:'Find women’s rugby fixtures and official broadcasts from around the world.', matches:[['England','France','TODAY · 15:00 UTC',false,'World Rugby','https://www.world.rugby/tournaments'],['New Zealand','Canada','SUNDAY · 12:00 UTC',false,'World Rugby','https://www.world.rugby/tournaments']] },
  tests: { name:'Test Matches', short:'TEST RUGBY', intro:'Rugby at its most meaningful.', description:'Follow international test rugby with official match coverage and global viewing links.', matches:[['South Africa','New Zealand','LIVE · 1ST HALF · 31:42',true,'World Rugby','https://www.world.rugby/tournaments'],['Ireland','Australia','SATURDAY · 16:00 UTC',false,'World Rugby','https://www.world.rugby/tournaments']] }
};
const league = leagues[document.body.dataset.league];
if (document.querySelector('#league-page')) {
  document.querySelector('#league-page').innerHTML = `<div class="app-shell"><header class="topbar"><a class="brand" href="index.html"><span class="brand-mark">↗</span><span>open<span>rugby</span></span></a><nav class="main-nav"><a href="index.html#matches">Matches</a><a class="active" href="index.html#leagues">Leagues</a><a href="index.html#how-it-works">How it works</a></nav><div class="top-actions"><a class="icon-button" href="index.html#matches" aria-label="Back to matches">←</a><button class="avatar">JD</button></div></header><main><section class="league-hero"><p class="eyebrow"><span class="pulse"></span><span id="league-short"></span> competition page</p><h1 id="league-name"></h1><p id="league-intro" class="league-intro"></p><p id="league-description" class="hero-text"></p><div class="hero-stats"><div><strong id="match-count"></strong><span>fixtures listed</span></div><div><strong>01</strong><span>live now</span></div><div><strong>100%</strong><span>official links</span></div></div></section><section class="toolbar-section"><div class="section-heading"><div><p class="eyebrow">The schedule</p><h2>Every fixture</h2></div><a class="text-link" href="index.html#matches">All matches →</a></div></section><section class="match-grid" id="league-grid"></section></main><footer><span class="brand small"><span class="brand-mark">↗</span><span>open<span>rugby</span></span></span><span>Free to find. Official to watch.</span><span>© 2026 OpenRugby</span></footer></div><div class="player-modal" id="player-modal" aria-hidden="true" role="dialog"><div class="player-panel"><button class="modal-close" id="close-player" aria-label="Close player">×</button><p class="eyebrow"><span class="pulse"></span> Official broadcast</p><h2 id="player-title">Ready to watch</h2><div class="player-screen"><span class="player-ball">◉</span><span>Stream available from the rights holder</span></div><p class="player-copy">OpenRugby links you to the authorized broadcaster in your region. Availability may vary by location.</p><a class="watch-button player-link" id="player-link" href="#" target="_blank" rel="noopener">Open official stream ↗</a></div></div><div class="toast" id="toast"></div>`;
}
document.querySelectorAll('.brand').forEach(brand => { const name = brand.querySelector('span:last-child'); if (name) name.innerHTML = 'free<span>rugby live</span>'; });
document.querySelectorAll('.brand').forEach(brand => brand.setAttribute('aria-label', 'Free Rugby Live home'));
document.querySelector('footer > span:last-child').textContent = '© 2026 Free Rugby Live';
document.querySelector('.player-panel .eyebrow').innerHTML = '<span class="pulse"></span> On Free Rugby Live';
document.querySelector('.player-copy').textContent = 'Live viewing stays on this page when a licensed broadcaster embed is available.';
document.title = `Free Rugby Live — ${league.name}`;
document.querySelector('#league-name').textContent = league.name;
document.querySelector('#league-short').textContent = league.short;
document.querySelector('#league-intro').textContent = league.intro;
document.querySelector('#league-description').textContent = league.description;
document.querySelector('#match-count').textContent = String(league.matches.length).padStart(2,'0');
document.querySelector('.hero-stats div:nth-child(2) strong').textContent = String(league.matches.filter(match => match[3]).length).padStart(2,'0');
const grid = document.querySelector('#league-grid');
const saved = new Set();
function teamBadge(name, side) { const initials = name.split(' ').map(word => word[0]).join('').slice(0, 3); return `<span class="team-cell ${side}"><span class="team-logo ${side}" aria-hidden="true">${initials}</span><span class="team">${name}</span></span>`; }
grid.innerHTML = league.matches.map(match => `<article class="match-card"><div><div class="match-top"><span class="league">${league.short}</span><div><span class="${match[3] ? 'live-tag' : 'league'}">${match[3] ? 'Live now' : 'Scheduled'}</span><button class="save" data-save="${match[0]}" aria-label="Save ${match[0]} match">♡</button></div></div><p class="match-time">${match[2]}</p><div class="teams">${teamBadge(match[0], 'home')}<span class="versus">VS</span>${teamBadge(match[1], 'away')}</div></div><div class="match-bottom"><span class="provider">FREE · ${match[4]}</span><button class="watch-button" data-watch="${match[5]}" data-embed="${match[6] || ''}" data-name="${match[0]} v ${match[1]}">${match[3] ? 'Watch live ↗' : 'Set reminder'}</button></div></article>`).join('');
const modal = document.querySelector('#player-modal');
const playerScreen = document.querySelector('#player-screen') || modal.querySelector('.player-screen');
const playerFrame = document.querySelector('#player-frame') || Object.assign(document.createElement('iframe'), { id:'player-frame', title:'Live rugby stream', allow:'autoplay; fullscreen; picture-in-picture' });
const playerStatus = document.querySelector('#player-status') || playerScreen.querySelector('span:last-child');
const playerCopy = document.querySelector('#player-copy') || modal.querySelector('.player-copy');
playerScreen.id = 'player-screen'; playerFrame.id = 'player-frame'; playerStatus.id = 'player-status'; playerCopy.id = 'player-copy'; if (!playerFrame.parentElement) playerScreen.appendChild(playerFrame);
grid.addEventListener('click', event => { const save = event.target.closest('[data-save]'); if (save) { saved.has(save.dataset.save) ? saved.delete(save.dataset.save) : saved.add(save.dataset.save); save.classList.toggle('saved'); save.textContent = saved.has(save.dataset.save) ? '♥' : '♡'; return; } const watch = event.target.closest('[data-watch]'); if (!watch) return; if (watch.textContent.includes('reminder')) { document.querySelector('#toast').textContent = `Reminder set for ${watch.dataset.name}`; document.querySelector('#toast').classList.add('show'); setTimeout(() => document.querySelector('#toast').classList.remove('show'), 2800); return; } document.querySelector('#player-title').textContent = watch.dataset.name; playerFrame.hidden = !watch.dataset.embed; document.querySelector('#player-link').hidden = !watch.dataset.embed; playerStatus.textContent = watch.dataset.embed ? 'Live stream' : 'Licensed stream embed pending'; playerCopy.textContent = watch.dataset.embed ? 'You are watching an authorized broadcast inside Free Rugby Live.' : 'This match is listed, but its licensed in-page stream has not been connected yet. No external redirect was used.'; if (watch.dataset.embed) playerFrame.src = watch.dataset.embed; else playerFrame.removeAttribute('src'); modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); });
function closePlayer() { modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); playerFrame.removeAttribute('src'); }
document.querySelector('#close-player').addEventListener('click', closePlayer); modal.addEventListener('click', event => { if (event.target === modal) closePlayer(); });
const authScript = document.createElement('script'); authScript.src = 'auth.js'; document.body.appendChild(authScript);
